language: python

python:
  - "2.7"
  - "3.5"

cache: pip

machine:
  pre:
    - pyenv install 3.5
    - virtualenv venv

install:
  - pip install image
  - pip install recordtype

script:
  - python -m unittest discover test -v
